package repositories

import (
	"log"

	"umrah/app/models"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

var DB *gorm.DB

func InitDB() {
	var err error
	DB, err = gorm.Open(sqlite.Open("data/umrah.db"), &gorm.Config{})
	if err != nil {
		log.Fatal("failed to connect database:", err)
	}

	DB.AutoMigrate(&models.Travel{}, &models.Package{}, &models.DetailPackage{})

	if DB.Migrator().HasTable(&models.Package{}) {
		var count int64
		DB.Model(&models.Package{}).Count(&count)
		if count == 0 {
			seedData()
		}
	}
}

func seedData() {
	travels := []models.Travel{
		{Name: "Al Haramain Travel", Rating: 4.8},
		{Name: "Nurul Iman Wisata", Rating: 4.6},
		{Name: "Madinah Tour & Travel", Rating: 4.7},
		{Name: "Baitullah Sejahtera", Rating: 4.5},
		{Name: "Zamzam Berkah Wisata", Rating: 4.4},
		{Name: "Hijrah Mulia Travel", Rating: 4.9},
		{Name: "Safa Marwah Tour", Rating: 4.3},
		{Name: "Arafah Indah Travel", Rating: 4.6},
	}
	DB.Create(&travels)

	packages := []models.Package{
		// HARGA 20-25 JT
		{TravelID: 7, Name: "Paket Murah Berkah", Price: 21000000, HotelDistance: 1300, Duration: 9, Airline: "Lion Air", IsDirect: false, DownPayment: 3000000, PaymentDeadline: "2025-11-05", Guide: "Ust. Zainal Abidin", Facilities: `["Visa","Hotel bintang 2","Transportasi bus","Makan 3x sehari"]`, IsFamily: false, IsSenior: false, SunnahScore: 6, GroupSize: 65, IsNearHaram: false, IsKajian: false, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 5, Name: "Paket Ramah Kantong", Price: 22000000, HotelDistance: 1100, Duration: 9, Airline: "AirAsia", IsDirect: false, DownPayment: 3000000, PaymentDeadline: "2025-11-10", Guide: "Ust. Fikri Haikal", Facilities: `["Visa","Hotel bintang 2","Transportasi bus","Makan 3x sehari"]`, IsFamily: false, IsSenior: true, SunnahScore: 5, GroupSize: 55, IsNearHaram: false, IsKajian: false, IsSunnah: false, IsKidFriendly: false, IsSeniorFriendly: true},
		{TravelID: 1, Name: "Paket Hemat", Price: 23000000, HotelDistance: 1200, Duration: 9, Airline: "Batik Air", IsDirect: false, DownPayment: 4000000, PaymentDeadline: "2025-11-15", Guide: "Ust. Muhammad Rizal", Facilities: `["Visa","Hotel bintang 2","Transportasi bus","Makan 3x sehari"]`, IsFamily: false, IsSenior: false, SunnahScore: 6, GroupSize: 60, IsNearHaram: false, IsKajian: false, IsSunnah: false, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 2, Name: "Paket Ekonomi", Price: 24000000, HotelDistance: 900, Duration: 9, Airline: "Saudia", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-11-20", Guide: "Ust. Harun Al Rasyid", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Manasik umrah"]`, IsFamily: false, IsSenior: false, SunnahScore: 7, GroupSize: 45, IsNearHaram: false, IsKajian: false, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 6, Name: "Paket Ekonomi Plus", Price: 24000000, HotelDistance: 800, Duration: 9, Airline: "Citilink", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-11-25", Guide: "Ust. Faisal Hakim", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Air zamzam"]`, IsFamily: true, IsSenior: false, SunnahScore: 7, GroupSize: 40, IsNearHaram: false, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},
		{TravelID: 8, Name: "Paket Ekonomi Dekat Haram", Price: 25000000, HotelDistance: 500, Duration: 9, Airline: "Lion Air", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-11-15", Guide: "Ust. Rahmat Hidayat", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Air zamzam"]`, IsFamily: false, IsSenior: false, SunnahScore: 7, GroupSize: 45, IsNearHaram: true, IsKajian: false, IsSunnah: false, IsKidFriendly: false, IsSeniorFriendly: false},

		// HARGA 25-30 JT
		{TravelID: 1, Name: "Paket Reguler", Price: 25000000, HotelDistance: 1000, Duration: 9, Airline: "Lion Air", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-12-01", Guide: "Ust. Ahmad Fauzi", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Air zamzam"]`, IsFamily: false, IsSenior: false, SunnahScore: 7, GroupSize: 50, IsNearHaram: false, IsKajian: false, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 8, Name: "Paket Tabungan", Price: 25000000, HotelDistance: 750, Duration: 9, Airline: "Citilink", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-11-20", Guide: "Ust. Hamzah Al Habsyi", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Manasik umrah"]`, IsFamily: false, IsSenior: false, SunnahScore: 7, GroupSize: 40, IsNearHaram: false, IsKajian: false, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 4, Name: "Paket Ekonomi Syariah", Price: 26000000, HotelDistance: 800, Duration: 9, Airline: "Saudia", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-11-25", Guide: "Ust. Syamsul Arifin", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Manasik umrah","Kajian rutin"]`, IsFamily: false, IsSenior: false, SunnahScore: 8, GroupSize: 40, IsNearHaram: false, IsKajian: true, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 3, Name: "Paket Lansia Hemat", Price: 26000000, HotelDistance: 750, Duration: 9, Airline: "Batik Air", IsDirect: false, DownPayment: 5000000, PaymentDeadline: "2025-11-20", Guide: "Ust. Nur Rahman", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Kursi roda","Pendamping lansia"]`, IsFamily: false, IsSenior: true, SunnahScore: 7, GroupSize: 35, IsNearHaram: false, IsKajian: false, IsSunnah: false, IsKidFriendly: false, IsSeniorFriendly: true},
		{TravelID: 2, Name: "Paket Kajian Hemat", Price: 27000000, HotelDistance: 700, Duration: 9, Airline: "Batik Air", IsDirect: false, DownPayment: 6000000, PaymentDeadline: "2025-12-01", Guide: "Ust. Imam Ghazali", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Kajian rutin","Manasik umrah"]`, IsFamily: false, IsSenior: false, SunnahScore: 9, GroupSize: 35, IsNearHaram: false, IsKajian: true, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 7, Name: "Paket Keluarga Hemat", Price: 27000000, HotelDistance: 600, Duration: 12, Airline: "Garuda Indonesia", IsDirect: false, DownPayment: 6000000, PaymentDeadline: "2025-12-05", Guide: "Ust. Malik Ibrahim", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan prasmanan","Air zamzam","Taman bermain anak"]`, IsFamily: true, IsSenior: false, SunnahScore: 7, GroupSize: 32, IsNearHaram: false, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},
		{TravelID: 3, Name: "Paket Standar", Price: 27000000, HotelDistance: 700, Duration: 9, Airline: "Citilink", IsDirect: false, DownPayment: 6000000, PaymentDeadline: "2025-12-01", Guide: "Ust. Hasan Basri", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Kursi roda","Pendamping lansia"]`, IsFamily: false, IsSenior: true, SunnahScore: 8, GroupSize: 35, IsNearHaram: false, IsKajian: false, IsSunnah: false, IsKidFriendly: false, IsSeniorFriendly: true},
		{TravelID: 5, Name: "Paket Dekat Haram Hemat", Price: 28000000, HotelDistance: 400, Duration: 9, Airline: "Garuda Indonesia", IsDirect: false, DownPayment: 7000000, PaymentDeadline: "2025-12-01", Guide: "Ust. Lutfi Hamid", Facilities: `["Visa","Hotel bintang 4","Transportasi bus","Makan 3x sehari","Air zamzam"]`, IsFamily: false, IsSenior: false, SunnahScore: 7, GroupSize: 35, IsNearHaram: true, IsKajian: false, IsSunnah: false, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 1, Name: "Paket Keluarga", Price: 28000000, HotelDistance: 600, Duration: 12, Airline: "Garuda Indonesia", IsDirect: true, DownPayment: 7000000, PaymentDeadline: "2025-12-10", Guide: "Ust. Abdullah Syahid", Facilities: `["Visa","Hotel bintang 4","Transportasi bus VIP","Makan prasmanan","Air zamzam","Kajian harian","Taman bermain anak"]`, IsFamily: true, IsSenior: false, SunnahScore: 8, GroupSize: 30, IsNearHaram: true, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},
		{TravelID: 7, Name: "Paket Pertengahan", Price: 29000000, HotelDistance: 550, Duration: 9, Airline: "Batik Air", IsDirect: false, DownPayment: 7000000, PaymentDeadline: "2025-12-05", Guide: "Ust. Hanan Attaki", Facilities: `["Visa","Hotel bintang 3","Transportasi bus","Makan 3x sehari","Air zamzam","Kajian rutin"]`, IsFamily: true, IsSenior: false, SunnahScore: 7, GroupSize: 30, IsNearHaram: false, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},
		{TravelID: 5, Name: "Paket Keluarga Bahagia", Price: 29000000, HotelDistance: 500, Duration: 12, Airline: "Garuda Indonesia", IsDirect: true, DownPayment: 7000000, PaymentDeadline: "2025-12-05", Guide: "Ust. Ridwan Hamid", Facilities: `["Visa","Hotel bintang 4","Transportasi bus VIP","Makan prasmanan","Air zamzam","Kajian harian","Taman bermain anak"]`, IsFamily: true, IsSenior: false, SunnahScore: 8, GroupSize: 28, IsNearHaram: true, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},

		// HARGA 30-40 JT
		{TravelID: 2, Name: "Paket Plus", Price: 30000000, HotelDistance: 400, Duration: 12, Airline: "Garuda Indonesia", IsDirect: true, DownPayment: 8000000, PaymentDeadline: "2025-12-05", Guide: "Ust. Ibrahim Khalil", Facilities: `["Visa","Hotel bintang 4","Transportasi bus VIP","Makan prasmanan","Air zamzam","Kajian harian","Ziarah tambahan"]`, IsFamily: true, IsSenior: false, SunnahScore: 8, GroupSize: 25, IsNearHaram: true, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},
		{TravelID: 8, Name: "Paket Nyaman", Price: 31000000, HotelDistance: 350, Duration: 12, Airline: "Garuda Indonesia", IsDirect: true, DownPayment: 8000000, PaymentDeadline: "2025-12-05", Guide: "Ust. Ali Hasan", Facilities: `["Visa","Hotel bintang 4","Transportasi bus VIP","Makan prasmanan","Air zamzam","Kajian harian","Ziarah tambahan","Taman bermain anak"]`, IsFamily: true, IsSenior: false, SunnahScore: 8, GroupSize: 22, IsNearHaram: true, IsKajian: true, IsSunnah: false, IsKidFriendly: true, IsSeniorFriendly: false},
		{TravelID: 3, Name: "Paket Lansia", Price: 32000000, HotelDistance: 300, Duration: 12, Airline: "Garuda Indonesia", IsDirect: true, DownPayment: 8000000, PaymentDeadline: "2025-12-10", Guide: "Ust. Ahmad Dahlan", Facilities: `["Visa","Hotel bintang 4","Transportasi bus VIP","Makan prasmanan","Air zamzam","Kajian harian","Pendamping lansia 24 jam","Kursi roda","Check-up kesehatan"]`, IsFamily: false, IsSenior: true, SunnahScore: 9, GroupSize: 20, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: true},
		{TravelID: 6, Name: "Paket Golden", Price: 34000000, HotelDistance: 250, Duration: 12, Airline: "Saudia", IsDirect: true, DownPayment: 10000000, PaymentDeadline: "2025-12-10", Guide: "Ust. Salman Al Farisi", Facilities: `["Visa","Hotel bintang 5","Transportasi bus VIP","Makan prasmanan premium","Air zamzam","Kajian eksklusif","Pendamping lansia","Kursi roda"]`, IsFamily: false, IsSenior: true, SunnahScore: 9, GroupSize: 18, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: true},
		{TravelID: 2, Name: "Paket Premium", Price: 35000000, HotelDistance: 200, Duration: 12, Airline: "Saudia", IsDirect: true, DownPayment: 10000000, PaymentDeadline: "2025-12-15", Guide: "Ust. Yusuf Mansur", Facilities: `["Visa","Hotel bintang 5","Transportasi bus VIP","Makan prasmanan premium","Air zamzam","Kajian eksklusif","Ziarah VIP","Oleh-oleh"]`, IsFamily: false, IsSenior: false, SunnahScore: 9, GroupSize: 15, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 4, Name: "Paket Eksklusif", Price: 38000000, HotelDistance: 150, Duration: 12, Airline: "Qatar Airways", IsDirect: true, DownPayment: 12000000, PaymentDeadline: "2025-12-15", Guide: "Ust. Arif Rahman", Facilities: `["Visa","Hotel bintang 5","Transportasi private","Makan prasmanan premium","Air zamzam","Kajian eksklusif","Ziarah VIP","Oleh-oleh","Foto dokumentasi"]`, IsFamily: false, IsSenior: false, SunnahScore: 10, GroupSize: 12, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: false, IsSeniorFriendly: false},
		{TravelID: 8, Name: "Paket Exclusive", Price: 39000000, HotelDistance: 120, Duration: 12, Airline: "Saudia", IsDirect: true, DownPayment: 12000000, PaymentDeadline: "2025-12-15", Guide: "Ust. Abdul Somad", Facilities: `["Visa","Hotel bintang 5","Transportasi private","Makan prasmanan premium","Air zamzam","Kajian eksklusif","Ziarah VIP","Oleh-oleh","Pendamping lansia","Taman bermain anak"]`, IsFamily: true, IsSenior: true, SunnahScore: 10, GroupSize: 10, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: true, IsSeniorFriendly: true},

		// HARGA 40 JT+
		{TravelID: 3, Name: "Paket VIP", Price: 40000000, HotelDistance: 100, Duration: 15, Airline: "Emirates", IsDirect: true, DownPayment: 15000000, PaymentDeadline: "2025-12-20", Guide: "Ust. Abdurrahman As-Sudais", Facilities: `["Visa","Hotel bintang 5","Transportasi private","Makan prasmanan premium","Air zamzam","Kajian eksklusif","Ziarah VIP","Oleh-oleh","Pendamping lansia","Taman bermain anak"]`, IsFamily: true, IsSenior: true, SunnahScore: 10, GroupSize: 10, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: true, IsSeniorFriendly: true},
		{TravelID: 6, Name: "Paket Platinum", Price: 42000000, HotelDistance: 100, Duration: 15, Airline: "Emirates", IsDirect: true, DownPayment: 15000000, PaymentDeadline: "2025-12-20", Guide: "Ust. Khalid Basalamah", Facilities: `["Visa","Hotel bintang 5","Transportasi private","Makan prasmanan premium","Air zamzam","Kajian eksklusif","Ziarah VIP","Oleh-oleh","Pendamping lansia","Taman bermain anak","Foto dokumentasi","Catering khusus"]`, IsFamily: true, IsSenior: true, SunnahScore: 10, GroupSize: 8, IsNearHaram: true, IsKajian: true, IsSunnah: true, IsKidFriendly: true, IsSeniorFriendly: true},
	}
	DB.Create(&packages)

	details := []models.DetailPackage{
		{PackageID: 1, DepartureDate: "2026-03-01", ReturnDate: "2026-03-10", HotelMakkah: "Rehab Al Janadriyah", HotelMadinah: "Al Rawda International", StarsMakkah: 2, StarsMadinah: 2, RoomType: "Quad", TotalQuota: 65, AvailableQuota: 50, DepartureLocation: "Surabaya", AddonTriple: 1000000, AddonDouble: 2000000, Guide: "Ust. Zainal Abidin"},
		{PackageID: 2, DepartureDate: "2026-02-05", ReturnDate: "2026-02-14", HotelMakkah: "Al Salam Hotel", HotelMadinah: "Zowar International", StarsMakkah: 2, StarsMadinah: 2, RoomType: "Quad", TotalQuota: 55, AvailableQuota: 40, DepartureLocation: "Surabaya", AddonTriple: 1000000, AddonDouble: 2000000, Guide: "Ust. Fikri Haikal"},
		{PackageID: 3, DepartureDate: "2026-02-10", ReturnDate: "2026-02-19", HotelMakkah: "Al Massa Grand", HotelMadinah: "Al Eiman Royal", StarsMakkah: 2, StarsMadinah: 2, RoomType: "Quad", TotalQuota: 60, AvailableQuota: 48, DepartureLocation: "Jakarta", AddonTriple: 1000000, AddonDouble: 2000000, Guide: "Ust. Muhammad Rizal"},
		{PackageID: 4, DepartureDate: "2026-03-05", ReturnDate: "2026-03-14", HotelMakkah: "Elaf Kinda", HotelMadinah: "Al Eiman Taibah", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 45, AvailableQuota: 28, DepartureLocation: "Surabaya", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Harun Al Rasyid"},
		{PackageID: 5, DepartureDate: "2026-04-01", ReturnDate: "2026-04-10", HotelMakkah: "Al Shohada Hotel", HotelMadinah: "Al Andalus Palace", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 40, AvailableQuota: 20, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Faisal Hakim"},
		{PackageID: 6, DepartureDate: "2026-04-10", ReturnDate: "2026-04-19", HotelMakkah: "Al Tawfiq Tower", HotelMadinah: "Dar Al Taqwa", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 45, AvailableQuota: 30, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Rahmat Hidayat"},
		{PackageID: 7, DepartureDate: "2026-01-15", ReturnDate: "2026-01-24", HotelMakkah: "Al Kiswah Tower", HotelMadinah: "Al Haram Hotel", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 50, AvailableQuota: 35, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 3000000, Guide: "Ust. Ahmad Fauzi"},
		{PackageID: 8, DepartureDate: "2026-02-25", ReturnDate: "2026-03-06", HotelMakkah: "Al Tawfiq Tower", HotelMadinah: "Al Andalus Palace", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 40, AvailableQuota: 25, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 3000000, Guide: "Ust. Hamzah Al Habsyi"},
		{PackageID: 9, DepartureDate: "2026-03-10", ReturnDate: "2026-03-19", HotelMakkah: "Al Shohada Hotel", HotelMadinah: "Al Mukhtara International", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 40, AvailableQuota: 18, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Syamsul Arifin"},
		{PackageID: 10, DepartureDate: "2026-03-15", ReturnDate: "2026-03-24", HotelMakkah: "Al Marwa Rayhaan", HotelMadinah: "Dar Al Taqwa", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 35, AvailableQuota: 15, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Nur Rahman"},
		{PackageID: 11, DepartureDate: "2026-04-05", ReturnDate: "2026-04-14", HotelMakkah: "Al Safwah Royal Orchid", HotelMadinah: "Al Eiman Royal", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 35, AvailableQuota: 20, DepartureLocation: "Surabaya", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Imam Ghazali"},
		{PackageID: 12, DepartureDate: "2026-04-05", ReturnDate: "2026-04-17", HotelMakkah: "Makkah Towers", HotelMadinah: "Madinah Hilton", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 32, AvailableQuota: 18, DepartureLocation: "Jakarta", AddonTriple: 1500000, AddonDouble: 3000000, Guide: "Ust. Malik Ibrahim"},
		{PackageID: 13, DepartureDate: "2026-01-10", ReturnDate: "2026-01-19", HotelMakkah: "Al Marwa Rayhaan", HotelMadinah: "Dar Al Taqwa", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 35, AvailableQuota: 22, DepartureLocation: "Surabaya", AddonTriple: 1500000, AddonDouble: 3000000, Guide: "Ust. Hasan Basri"},
		{PackageID: 14, DepartureDate: "2026-04-10", ReturnDate: "2026-04-19", HotelMakkah: "Hilton Suites Makkah", HotelMadinah: "Al Haram Hotel", StarsMakkah: 4, StarsMadinah: 4, RoomType: "Quad", TotalQuota: 35, AvailableQuota: 20, DepartureLocation: "Jakarta", AddonTriple: 2000000, AddonDouble: 4000000, Guide: "Ust. Lutfi Hamid"},
		{PackageID: 15, DepartureDate: "2026-01-20", ReturnDate: "2026-02-01", HotelMakkah: "Swissotel Makkah", HotelMadinah: "Dallah Taibah", StarsMakkah: 4, StarsMadinah: 4, RoomType: "Quad", TotalQuota: 30, AvailableQuota: 12, DepartureLocation: "Jakarta", AddonTriple: 2000000, AddonDouble: 4000000, Guide: "Ust. Abdullah Syahid"},
		{PackageID: 16, DepartureDate: "2026-03-20", ReturnDate: "2026-03-29", HotelMakkah: "Al Safwah Royal Orchid", HotelMadinah: "Al Eiman Royal", StarsMakkah: 3, StarsMadinah: 3, RoomType: "Quad", TotalQuota: 30, AvailableQuota: 15, DepartureLocation: "Surabaya", AddonTriple: 1500000, AddonDouble: 2500000, Guide: "Ust. Hanan Attaki"},
		{PackageID: 17, DepartureDate: "2026-03-20", ReturnDate: "2026-04-01", HotelMakkah: "Makkah Towers", HotelMadinah: "Madinah Hilton", StarsMakkah: 4, StarsMadinah: 4, RoomType: "Quad", TotalQuota: 28, AvailableQuota: 10, DepartureLocation: "Jakarta", AddonTriple: 2000000, AddonDouble: 4000000, Guide: "Ust. Ridwan Hamid"},
		{PackageID: 18, DepartureDate: "2026-02-15", ReturnDate: "2026-02-27", HotelMakkah: "Hilton Suites Makkah", HotelMadinah: "Crowne Plaza Madinah", StarsMakkah: 4, StarsMadinah: 4, RoomType: "Quad", TotalQuota: 25, AvailableQuota: 8, DepartureLocation: "Jakarta", AddonTriple: 2500000, AddonDouble: 5000000, Guide: "Ust. Ibrahim Khalil"},
		{PackageID: 19, DepartureDate: "2026-03-15", ReturnDate: "2026-03-27", HotelMakkah: "Hyatt Regency Makkah", HotelMadinah: "Millennium Al Aqeeq", StarsMakkah: 4, StarsMadinah: 4, RoomType: "Quad", TotalQuota: 22, AvailableQuota: 9, DepartureLocation: "Jakarta", AddonTriple: 2000000, AddonDouble: 4000000, Guide: "Ust. Ali Hasan"},
		{PackageID: 20, DepartureDate: "2026-02-20", ReturnDate: "2026-03-04", HotelMakkah: "Makkah Grand Coral", HotelMadinah: "Al Madinah Harmony", StarsMakkah: 4, StarsMadinah: 4, RoomType: "Quad", TotalQuota: 20, AvailableQuota: 5, DepartureLocation: "Jakarta", AddonTriple: 2000000, AddonDouble: 4000000, Guide: "Ust. Ahmad Dahlan"},
		{PackageID: 21, DepartureDate: "2026-04-10", ReturnDate: "2026-04-22", HotelMakkah: "Le Meridien Makkah", HotelMadinah: "Anwar Al Madinah", StarsMakkah: 5, StarsMadinah: 5, RoomType: "Triple", TotalQuota: 18, AvailableQuota: 7, DepartureLocation: "Jakarta", AddonTriple: 3000000, AddonDouble: 5500000, Guide: "Ust. Salman Al Farisi"},
		{PackageID: 22, DepartureDate: "2026-04-01", ReturnDate: "2026-04-13", HotelMakkah: "Conrad Makkah", HotelMadinah: "Shaza Al Madinah", StarsMakkah: 5, StarsMadinah: 5, RoomType: "Double", TotalQuota: 15, AvailableQuota: 6, DepartureLocation: "Jakarta", AddonTriple: 3000000, AddonDouble: 6000000, Guide: "Ust. Yusuf Mansur"},
		{PackageID: 23, DepartureDate: "2026-04-15", ReturnDate: "2026-04-27", HotelMakkah: "Movenpick Makkah", HotelMadinah: "Pullman Zamzam Madinah", StarsMakkah: 5, StarsMadinah: 5, RoomType: "Triple", TotalQuota: 12, AvailableQuota: 4, DepartureLocation: "Jakarta", AddonTriple: 3000000, AddonDouble: 6000000, Guide: "Ust. Arif Rahman"},
		{PackageID: 24, DepartureDate: "2026-04-20", ReturnDate: "2026-05-02", HotelMakkah: "Swissotel Al Maqam", HotelMadinah: "Al Haram Hotel", StarsMakkah: 5, StarsMadinah: 5, RoomType: "Triple", TotalQuota: 10, AvailableQuota: 4, DepartureLocation: "Jakarta", AddonTriple: 3500000, AddonDouble: 7000000, Guide: "Ust. Abdul Somad"},
		{PackageID: 25, DepartureDate: "2026-05-01", ReturnDate: "2026-05-16", HotelMakkah: "Fairmont Makkah", HotelMadinah: "Oberoi Madinah", StarsMakkah: 5, StarsMadinah: 5, RoomType: "Double", TotalQuota: 10, AvailableQuota: 3, DepartureLocation: "Jakarta", AddonTriple: 4000000, AddonDouble: 8000000, Guide: "Ust. Abdurrahman As-Sudais"},
		{PackageID: 26, DepartureDate: "2026-06-01", ReturnDate: "2026-06-16", HotelMakkah: "Raffles Makkah Palace", HotelMadinah: "Dar Al Iman InterContinental", StarsMakkah: 5, StarsMadinah: 5, RoomType: "Double", TotalQuota: 8, AvailableQuota: 2, DepartureLocation: "Jakarta", AddonTriple: 5000000, AddonDouble: 10000000, Guide: "Ust. Khalid Basalamah"},
	}
	DB.Create(&details)

	log.Println("Database seeded with", len(travels), "travels,", len(packages), "packages, and", len(details), "details")
}
